orbs:
  node: circleci/node@4.1.0
  gcp-cli: circleci/gcp-cli@2.1.0

version: 2.1

jobs:
  lint:
    executor:
      name: node/default
      tag: 12
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
  deploy:
    executor:
      name: gcp-cli/google
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize
      - run:
          command: gcloud app deploy app.yaml

workflows:
  test-and-deploy:
    jobs:
      - lint
      - node/test:
          version: 12
      - deploy:
          requires:
            - lint
            - node/test
